name: test

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.6, 2.7, 3.0, 3.1, head]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Build
      run: |
        ruby extconf.rb
        make
    - name: Run the test suite
      run: |
        rake
